### ISSUE TITLE
Add ItemsAdder support.

### ISSUE THREAD

**Issue by dinobossytnew** [WeaponMechanics/MechanicsMain#125]
### Description

You could add itemsadder support because I see that every time I try to add a weapon to itemsadder so that the pack is sent through the itemsadder with the sound it also bugs and does not play if you can add support or a separate addon with textures and models, sounds would be very nice.

### Configuration

it would not be a configuration so I can't give an opinion on it but it would be an addon like many others [here](https://addons.devs.beer/itemsadder/).

**Comment by CJCrafter** [comment]
I'm not quite sure what the issue is you are describing. The server can only send one resource pack, so if you want a the server to send both the WeaponMechanics resource pack and the ItemsAdder resource pack, you'll have to combine them into one. If you need help with that, you should get in contact with the developer of ItemsAdder with us on our discord.

**Comment by CJCrafter** [comment]
Since no additional information as been provided, this issue is being closed. You may open a new issue with more information.
