### ISSUE TITLE
Improving drag and gravity of fast projectiles

### ISSUE THREAD

**Issue by TheRealDardan** [WeaponMechanics/MechanicsMain#339]
### Description

Drag and gravity are only applied to the projectile at the beginning of each projectile tick, this means if a projectile is fast enough it can cover a long distance before drag and gravity affect it. 

To illustrate i modelled the bullet drop of a 660m/s projectile with a drag coefficient of 0.98 and gravity of 9.8m/s^2

![image](https://i.gyazo.com/05d42c7fbc04efd91275f5df4de35b73.png)

As you can see the bullet can move around 44 blocks before it is affected

Now lets keep drag and gravity the same but reduce the initial velocity to 220m/s, you will see the drop is smoother.

![image2](https://i.gyazo.com/e94d4d4c05289a27a5f7e7716d85cb05.png)

if you are doubtful you can verify this ingame using a long lasting particle trail to make the effect more visible.

I cant think of a solution myself because we can't make bullets tick faster. However guncolony uses their own plugin which avoids this problem using , i quote ""[a sub-tick architecture with similarities to CS2's new system](https://youtu.be/vNC6weohxQA?t=39)". so i think it's possible technically.

### Configuration

-

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Lucky you, Zaify wants this implemented and paid for it to be implemented. Will keep this thread updated as I implement and test the solution.

**Comment by CJCrafter** [comment]
So we currently use the `EULER` method, since it is very fast. It works by applying the current acceleration to the velocity on every tick BEFORE applying the velocity to the position. But thinking about it... this means that the acceleration will be **OVERESTIMATED**... So shouldn't our projectile be **LOWER** then it is supposed to be?

So I compared `EULER` to `RUNGE-KUTTA`, which is more accurate since it "spreads out" the acceleration over the tick, instead of applying it before the tick starts, and here is the result (over 4 ticks):

![image](https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/095a751b-1721-483e-b397-955f7c39a0a5)

This is interesting since, according to this data, trying to make our code more accurate will make the projectile higher... Which means that there must be a bug in WeaponMechanics code. I decided to try to flip the `EULER` method, and apply the velocity to the position before the acceleration is applied to the velocity. This was the result:

![image](https://github.com/WeaponMechanics/MechanicsMain/assets/43940682/17145845-5573-4c60-98e5-884e035c085f)

Which definitely looks like the issue you pointed out! So to solve this issue, I need to:
1. Apply the Euler method correctly (Fixing the bug for low velocity projectiles)
2. for high velocity projectiles (`>500 m/s`), use the more accurate method

**Comment by CJCrafter** [comment]
@TheRealDardan Have you noticed the improvements in the new versions? Or do I need to take the position calculations further?

**Comment by CJCrafter** [comment]
```python
import matplotlib.pyplot as plt


class Vector():
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

    def __add__(self, other):
        if isinstance(other, Vector):
            return Vector(self.x + other.x, self.y + other.y)
        else:
            raise ValueError("Both operands must be of 'Vector' type")

    def __mul__(self, scalar):
        if isinstance(scalar, (int, float)):
            return Vector(self.x * scalar, self.y * scalar)
        else:
            raise ValueError("The scalar must be an integer or a float")

    def __rmul__(self, scalar):
        # This allows multiplication in both orders: vector * scalar and scalar * vector
        return self.__mul__(scalar)

    def __truediv__(self, scalar):
        if isinstance(scalar, (int, float)):
            return Vector(self.x / scalar, self.y / scalar)
        else:
            raise ValueError("The scalar must be an integer or a float")


g = Vector(0, -9.81)
dt = 1 / 20
ticks = 80

initial_projectile_speed = 10000

# Used to track euler
euler_position = Vector(0, 10)
euler_velocity = Vector(initial_projectile_speed, 0)

# used to track rungeKutta
runge_position = Vector(0, 10)
runge_velocity = Vector(initial_projectile_speed, 0)


# Define the Runge-Kutta function
def runge_kutta_step(s: Vector, v: Vector, a):
    k1_x = dt * v
    k1_v = dt * a

    k2_x = dt * (v + k1_v/2)
    k2_v = dt * a

    k3_x = dt * (v + k2_v/2)
    k3_v = dt * a

    k4_x = dt * (v + k3_v)
    k4_v = dt * a

    x_next = s + (k1_x + 2 * k2_x + 2 * k3_x + k4_x) / 6
    v_next = v + (k1_v + 2*k2_v + 2*k3_v + k4_v) / 6

    return x_next, v_next


# Lists to store positions and velocities for plotting
euler_position_list, runge_position_list = [], []

for i in range(ticks):
    # Basic Euler Method
    euler_velocity += g * dt
    euler_position += euler_velocity * dt

    # Runge Kutta Method
    runge_position, runge_velocity = runge_kutta_step(runge_position, runge_velocity, g)

    # Store values for plotting
    euler_position_list.append(euler_position * 1)
    runge_position_list.append(runge_position * 1)

# Create plots
fig, axs = plt.subplots(1)

# Position
euler_positions_x = [vector.x for vector in euler_position_list]
euler_positions_y = [vector.y for vector in euler_position_list]
runge_positions_x = [vector.x for vector in runge_position_list]
runge_positions_y = [vector.y for vector in runge_position_list]

# Use 'post' for horizontal line to the next x
axs.step(euler_positions_x, euler_positions_y, where='post', label='Euler')
axs.step(runge_positions_x, runge_positions_y, where='post', label='Runge-Kutta')

# Overplot open circles at the ends of the lines
axs.scatter(euler_positions_x, euler_positions_y, facecolors='none', edgecolors='C0')
axs.scatter(runge_positions_x, runge_positions_y, facecolors='none', edgecolors='C1')

axs.set_title('Position')
axs.set_xlabel('Distance Travelled (blocks)')
axs.set_ylabel('Y-Position Deviation (blocks)')
axs.legend()

plt.tight_layout()
plt.show()
```
Going to optimize a version of this for WM right now, here is the python code used to test runge-kutta and graph improvements

**Comment by CJCrafter** [comment]
Fixed.
